version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: flask_app
    environment:
      HOSTNAME: ${HOSTNAME}
      DATABASE: ${DATABASE}
      PORT: ${PORT}
      DB_USERNAME: ${DB_USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
